[package]
name = "korean_dictionary"
version = "0.3.0"
authors = ["Seungjae Park <astro.psj@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type=["dylib"]

[dependencies]
kodict = "0.2"
libc = "0.2"

[profile.release]
lto = true
